=head1 NAME

B<icalBuddy> -- query the OS X calendar database for items


=head1 SYNOPSIS

=over 10

=item B<icalBuddy>

[B<-Vufn>] [B<--strEncoding> I<encoding>] [B<-sc>] [B<-sd>] [B<-nc>] [B<-nrd>] [B<-li>] [B<-tf> I<format>] [B<-df> I<format>] [B<-po> I<value>] [B<-ps> I<value>] [B<-b> I<value>] [B<-ab> I<value>] [B<-ss> I<value>] [B<-ic> I<value>] [B<-ec> I<value>] [B<-iep> I<value>] [B<-eep> I<value>] [B<-itp> I<value>] [B<-etp> I<value>] [B<-cf> I<path>] [B<-lf> I<path>] [B<-nnr> I<value>] I<command>

=back

=head1 DESCRIPTION

B<icalBuddy> queries the OS X calendar database for items and outputs them.

The options are as follows:

=over 12

=item I<command>

Specifies the general action to take. Possible values are:

=over 24

=item B<C<eventsToday>>

Print events occurring today

=item B<C<eventsToday+NUM>>

Print events occurring between today and NUM days into the future, where NUM is an integer

=item B<C<eventsNow>>

Print events occurring at present time

=item B<C<eventsFrom:START to:END>>

Print events occurring between the two specified dates (START and END), where both are specified in the format C<YYYY-MM-DD HH:MM:SS +HHMM> (the C<+HHMM> part at the end specifies the timezone offset in hours and minutes from GMT, and it may have a plus or minus prefix)

=item B<C<uncompletedTasks>>

Print uncompleted tasks

=item B<C<calendars>>

Print a list of all the calendars

=item B<C<strEncodings>>

Print all the possible string encodings

=item B<C<editConfig>>

Open the configuration file for editing in a GUI editor application

=item B<C<editConfigCLI>>

Open the configuration file for editing in a command-line editor

=back


=item B<-V>, B<--version>

Print version number and exit.

=item B<-u>, B<--checkForUpdates>

Check for updates to self. Also allows for automatic updating of self (with minimal user interaction, straight from the command line.)

=item B<-sc>, B<--separateByCalendar>

Separate events/tasks in the output by calendar.

=item B<-sd>, B<--separateByDate>

Separate events/tasks in the output by date.

=item B<-f>, B<--formatOutput>

Use ANSI escape sequences to format the output and hopefully make it more readable.

=item B<-nc>, B<--noCalendarNames>

Omit calendar names from the output. Does not apply if the B<-sc> argument is used.




=item B<-nrd>, B<--noRelativeDates>

Do not use "natural language relative dates" when displaying dates (e.g. "today", "yesterday" or "day after tomorrow".)

=item B<-n>, B<--includeOnlyEventsFromNowOn>

If the I<command> value C<eventsToday> is used, only output events that occur between the current time and the end of the day (as opposed to events that occur between the start and end of the day, as by default.)

=item B<-li>, B<--limitItems> I<num>

Limit the number of printed items (events/tasks) in the output to a maximum of I<num> items.

=item B<--strEncoding> I<encoding>

Use the specified string encoding for the output. Run the app once with the 'strEncodings' I<command> value to see all the possible values you can use here.

=item B<-tf>, B<--timeFormat> I<format>

Format times included in the output based on the I<format> formatting string. See C<http://tinyurl.com/b9mgyp> [apple.com] for documentation on the syntax to use.

=item B<-df>, B<--dateFormat> I<format>

Format dates included in the output based on the I<format> formatting string. See C<http://tinyurl.com/b9mgyp> [apple.com] for documentation on the syntax to use.

=item B<-po>, B<--propertyOrder> I<value>

Print properties of events/tasks in the order specified by I<value>, which must be a comma-separated list of property names. The allowed property names are: title, location, notes, url, datetime, priority.

=item B<-ps>, B<--propertySeparators> I<value>

Use the strings specified in I<value> as the separators between item properties in the output. I<value> must be a list of strings where each component is separated by an arbitrary character that is present also as the first and the last character in the value (that means you can use any character you'd like as the separator, as long as you also use it at the beginning and the end.) The components specified in I<value> will be used in order, for each item, starting from the first printed property. If the number of printed properties for an item is bigger than the number of components in I<value>, the last component is used as the separator for the remaining properties. For example, a value of S<C<|, | - |>> would specify S<C<, >> as the separator between the first and the second property and S<C< - >> as the separator between all the rest of the properties. The default is S<C<|\\n    |>> (i.e. use a newline and four spaces as the separator for all properties.)

=item B<-b>, B<--bullet> I<value>

Sets I<value> as the string to be used as the bullet point in the output. The default is S<C<* >>.

=item B<-ab>, B<--alertBullet> I<value>

Sets I<value> as the string to be used as the alert bullet point in the output. The default is S<C<! >>.

=item B<-ss>, B<--sectionSeparator> I<value>

Sets I<value> as the string to be used as the section separator in the output. The default is a newline followed by a bunch of minus/dash (-) characters.

=item B<-ic>, B<--includeCals> I<value>

Includes only items in calendars specified by I<value> into the output. I<value> must be a comma-separated list of calendar UIDs (which you can find out by using the 'calendars' I<command> parameter.) You can also use titles, but remember that they may not be unique (as opposed to UIDs.) The B<-ic> and B<-ec> parameters will be handled in the order of first include, then exclude.

=item B<-ec>, B<--excludeCals> I<value>

Excludes items in calendars specified by I<value> from the output. I<value> must be a comma-separated list of calendar UIDs (which you can find out by using the 'calendars' I<command> parameter.) You can also use titles, but remember that they may not be unique (as opposed to UIDs.) The B<-ic> and B<-ec> parameters will be handled in the order of first include, then exclude.

=item B<-iep>, B<--includeEventProps> I<value>

Includes only event properties specified by I<value> into the output. I<value> must be a comma-separated list of property names. Possible property names are: location, url, notes, datetime, title.

=item B<-eep>, B<--excludeEventProps> I<value>

Excludes event properties specified by I<value> from the output. I<value> must be a comma-separated list of property names. See B<-iep> for a list of possible property names. A value of C<*> will exclude all properties and make sure just the title is printed.

=item B<-itp>, B<--includeTaskProps> I<value>

Includes only task properties specified by I<value> into the output. I<value> must be a comma-separated list of property names. Possible property names are: url, notes, datetime and priority.

=item B<-etp>, B<--excludeTaskProps> I<value>

Excludes task properties specified by I<value> from the output. I<value> must be a comma-separated list of property names. See B<-itp> for a list of possible property names. A value of C<*> will exclude all properties and make sure just the title is printed.

=item B<-cf>, B<--configFile> I<path>

Use the configuration file located at I<path> instead of the default one (F<~/.icalBuddyConfig.plist>). Pass in an empty string ("") to make icalBuddy ignore the configuration file completely.

=item B<-lf>, B<--localizationFile> I<path>

Use the localization file located at I<path> instead of the default one (F<~/.icalBuddyLocalization.plist>).

=item B<-nnr>, B<--notesNewlineReplacement> I<value>

Replaces newlines in values of the notes property with I<value>.


=back


=head1 EXAMPLES

	$ icalBuddy -sc uncompletedTasks

Outputs all uncompleted tasks, separated by calendar

	$ icalBuddy -sd -ic Work,Home -ec WeekNumbers eventsToday

Outputs all events occurring today from all calendars where the title or UID matches 'Work' or 'Home' and the title or UID does not match 'WeekNumbers', separated by date

	$ icalBuddy eventsFrom:"2009-01-01 00:00:00 +02:00" to:"2009-01-31 23:59:59 +02:00"

Outputs all events occurring between the first of january, 2009 and the 31st of january, 2009 (using the timezone GMT+02:00)



=head1 SEE ALSO

icalBuddyConfig(1), icalBuddyLocalization(1)

=head1 AUTHORS

This man page has been written by Ali Rantakari (http://hasseg.org)

